### ISSUE TITLE
implementar divisao por 0 :>

### ISSUE THREAD

**Issue by edenilsonjunior** [Felipe-Pestana/Calc#1]

**Comment by Felipe-Pestana** [comment]
https://training.github.com/downloads/github-git-cheat-sheet.pdf

**Comment by thavao** [comment]
😎

**Comment by Felipe-Pestana** [comment]
![WhatsApp Image 2024-04-09 at 15 45 54_1054ffeb](https://github.com/Felipe-Pestana/Calc/assets/78943604/c0e33dbd-f15c-4cf6-ae35-db31be2f572e)
